### ISSUE TITLE
Unable to install Shopware store packages with build flavor none

### ISSUE THREAD

**Issue by lruozzi9** [shopware/recipes#148]
If you run the recipe default applications.yaml for Shopware paas:
```yaml
-   name: app
    type: php:8.3
    build:
        flavor: none
```
It fails while installing dependencies from Shopware store.
Using `flavor: composer` works as expected.
