### ISSUE TITLE
shopware/paas session handling

### ISSUE THREAD

**Issue by 0x4** [shopware/recipes#176]
The paas recipe has only the "cacheredis" service which is not persistent 

```
cacheredis:
    type: redis:7.2
    configuration:
        maxmemory_policy: volatile-lfu
```

and that service is used for session storage in the paas.yaml

```
framework:
    session:
        handler_id: "%env(CACHE_URL)%/2"
```

shouldn't there be a second redis service which is persistent for session handling? or is my understanding of the platform.sh logic wrong that non-persistent redis can be cleared on deploys or some internal platform.sh relocations? Something like:

```
redissession:
    type: persistent-redis:7.2
    disk: ...
    configuration:
        maxmemory_policy: volatile-lfu
```

and then use that one?

```
framework:
    session:
        handler_id: "%env(SESSION_REDIS_URL)%/2"
```
