### ISSUE TITLE
MySQL default credentials for docker-compose setup

### ISSUE THREAD

**Issue by RafaelKr** [shopware/recipes#24]
Currently for local development we manually need to either add the environment variables for the database config to `docker-compose.override.yml` or adjust the credentials in the `.env` / `.env.local`

I'd suggest to add the following to `docker-compose.override.yml` via recipe for local development.

```yaml
###> shopware/core ###
  database:
    environment:
      MYSQL_DATABASE: shopware
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
###< shopware/core ###
```

I'm also open to do this another way, but we shouldn't need to change this to start with a fresh project.

Besides that I love that new flex approach, it's so much more convenient!

Edit:
Removed 
```yaml
      MYSQL_USER: root
      MYSQL_PASSWORD: root
```
which was working with my mariadb setup, but not with mysql.

Edit 2:
For mariadb:10.6 `MYSQL_USER` and `MYSQL_PASSWORD` are required btw
